In [5]:
import pandas as pd

In [6]:
ANO = 26
dataframe_dengue = pd.read_csv(f"./DENGBR{ANO}.CSV")
dataframe_dengue = dataframe_dengue.loc[dataframe_dengue["ID_MUNICIP"]==520870]
dataframe_dengue['ID_UNIDADE'] = dataframe_dengue['ID_UNIDADE'].astype('Int64') 
dataframe_dengue

C:\Users\Narut\AppData\Local\Temp\ipykernel_1040\3067636453.py:2: DtypeWarning: Columns (0: DT_NS1, 1: DT_VIRAL, 2: DT_OBITO) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe_dengue = pd.read_csv(f"./DENGBR{ANO}.CSV")

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N,DT_DIGITA,CS_FLXRET,FLXRECEBI,MIGRADO_W
6002,2,A90,2026-03-20,202611,2026,52,520870,1779,2518406,2026-03-18,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-03-20,0,NaN,NaN
6258,2,A90,2026-03-11,202610,2026,52,520870,1779,2339315,2026-03-07,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-03-11,0,NaN,NaN
6858,2,A90,2026-03-06,202609,2026,52,520870,1779,2339315,2026-03-03,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-03-06,0,NaN,NaN
7878,2,A90,2026-02-18,202607,2026,52,520870,1779,2506327,2026-02-17,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-02-26,1,NaN,NaN
9642,2,A90,2026-01-29,202604,2026,52,520870,1779,2506327,2026-01-29,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-02-07,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146043,2,A90,2026-02-27,202608,2026,52,520870,1779,2518406,2026-02-23,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-03-02,0,NaN,NaN
156992,2,A90,2026-03-13,202610,2026,52,520870,1779,2338556,2026-03-10,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-03-14,0,NaN,NaN
158016,2,A90,2026-03-09,202610,2026,52,520870,1779,2338556,2026-03-06,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-03-20,0,NaN,NaN
161651,2,A90,2026-02-21,202607,2026,52,520870,1779,2506661,2026-02-15,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-02-23,0,NaN,NaN
163825,2,A90,2026-01-12,202602,2026,52,520870,1779,2339552,2026-01-10,...,NaN,NaN,NaN,NaN,2.0,NaN,2026-01-23,1,NaN,NaN

In [7]:
dataframe_postos = pd.read_csv("./cnesDefinitvo.csv")
dataframe_postos

,UF,MUNICIPIO,CNES,NOME,NATUREZA,GESTÃO,ATENDE SUS
0,GO,GOIANIA,7966229,AEROMEDICO ASA ROTATIVA 01,ADMINISTRAÇÃO PÚBLICA,M,SIM
1,GO,GOIANIA,2339587,AMBULATORIO MUNICIPAL DE PSIQUIATRIA,ADMINISTRAÇÃO PÚBLICA,M,SIM
2,GO,GOIANIA,5684145,AMBULATORIO TRANSVIVER,ADMINISTRAÇÃO PÚBLICA,M,SIM
3,GO,GOIANIA,2339447,CAIS BAIRRO GOIA,ADMINISTRAÇÃO PÚBLICA,M,SIM
4,GO,GOIANIA,2339501,CAIS CAMPINAS,ADMINISTRAÇÃO PÚBLICA,M,SIM
...,...,...,...,...,...,...,...
250,GO,GOIANIA,2653893,USF VILA PEDROSO,ADMINISTRAÇÃO PÚBLICA,M,SIM
251,GO,GOIANIA,2339331,USF VILA REGINA,ADMINISTRAÇÃO PÚBLICA,M,SIM
252,GO,GOIANIA,2338548,USF VILA SANTA HELENA,ADMINISTRAÇÃO PÚBLICA,M,SIM
253,GO,GOIANIA,2653842,USF VILLE DE FRANCE,ADMINISTRAÇÃO PÚBLICA,M,SIM
254,GO,GOIANIA,2506939,USF WALDOMIRO CRUZ RESIDENCIAL ITAIPU,ADMINISTRAÇÃO PÚBLICA,M,SIM

In [12]:
COLUNAS_DO_DEFINITIVO = [
    'CNES',
    'TP_NOT',
    'DT_NOTIFIC',
    'NU_ANO',
    'ID_REGIONA',
    'ID_UNIDADE',
    'TP_SISTEMA'
]

dataframe_join = dataframe_dengue.merge(dataframe_postos, how="inner", left_on='ID_UNIDADE', right_on='CNES')
dataframe_join = dataframe_join[COLUNAS_DO_DEFINITIVO]

dataframe_join = dataframe_join.drop_duplicates()
dataframe_join.tail(200)

         CNES  TP_NOT  DT_NOTIFIC  NU_ANO  ID_REGIONA  ID_UNIDADE  TP_SISTEMA
6601  2626691       2  2026-01-11    2026        1779     2626691         2.0
6607  2339501       2  2026-01-10    2026        1779     2339501         2.0
6614  2339315       2  2026-01-17    2026        1779     2339315         2.0
6620  2338556       2  2026-02-09    2026        1779     2338556         2.0
6625  2339528       2  2026-01-07    2026        1779     2339528         2.0
...       ...     ...         ...     ...         ...         ...         ...
9189  6386369       2  2026-01-27    2026        1779     6386369         2.0
9199  2626691       2  2026-01-08    2026        1779     2626691         2.0
9207  2338556       2  2026-01-13    2026        1779     2338556         2.0
9210  2338556       2  2026-01-15    2026        1779     2338556         2.0
9235  4170431       2  2026-03-01    2026        1779     4170431         2.0

[200 rows x 7 columns]